import 'song.dart';

// Here I created separated playlists for differrent moods

List<Song> playlistHappy = [
  Song(
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    youtubeUrl: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
    spotifyUrl: 'https://open.spotify.com/track/7qiZfU4dY1lWllzX7nJf9u',
  ),
  Song(
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    youtubeUrl: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
    spotifyUrl: 'https://open.spotify.com/track/0fJuZ6zZABg9hUnyldG1p4',
  ),
  Song(
    title: 'Happy',
    artist: 'Pharrell Williams',
    youtubeUrl: 'https://www.youtube.com/watch?v=YQHsXMglC9A',
    spotifyUrl: 'https://open.spotify.com/track/6tFJ9IzPbaMbbFez22jV8C',
  ),
  Song(
    title: 'Can’t Stop the Feeling!',
    artist: 'Justin Timberlake',
    youtubeUrl: 'https://www.youtube.com/watch?v=ru0K8uYEZWw',
    spotifyUrl: 'https://open.spotify.com/track/7yOdUt4hzFzZySpj5vZPQg',
  ),
  Song(
    title: 'Uptown Funk',
    artist: 'Mark Ronson ft. Bruno Mars',
    youtubeUrl: 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
    spotifyUrl: 'https://open.spotify.com/track/32pOKqmvw33Jkt8wZROpv0',
  ),
  Song(
    title: 'Walking on Sunshine',
    artist: 'Katrina and the Waves',
    youtubeUrl: 'https://www.youtube.com/watch?v=iPUmE-tne5U',
    spotifyUrl: 'https://open.spotify.com/track/2D8YX2FjQ0WZLtIS3qf1w8',
  ),
  Song(
    title: 'Good as Hell',
    artist: 'Lizzo',
    youtubeUrl: 'https://www.youtube.com/watch?v=0F0CAEoF4z4',
    spotifyUrl: 'https://open.spotify.com/track/2R1Vv7ZSRkNo4zPljZ8Dz0',
  ),
  Song(
    title: 'Don’t Start Now',
    artist: 'Dua Lipa',
    youtubeUrl: 'https://www.youtube.com/watch?v=oygrmJFKYZY',
    spotifyUrl: 'https://open.spotify.com/track/0jctN0hMjbIxnMEByddNkd',
  ),
  Song(
    title: 'I Wanna Dance with Somebody',
    artist: 'Whitney Houston',
    youtubeUrl: 'https://www.youtube.com/watch?v=eH3giaIzONA',
    spotifyUrl: 'https://open.spotify.com/track/6bR2bmbWRv2FUtFEx1qlBo',
  ),
  Song(
    title: 'Wake Me Up',
    artist: 'Avicii',
    youtubeUrl: 'https://www.youtube.com/watch?v=IcrbM1l_BoI',
    spotifyUrl: 'https://open.spotify.com/track/4P1J1f84RoqmHYr5lANZYy',
  ),
  Song(
    title: 'Levitating',
    artist: 'Dua Lipa ft. DaBaby',
    youtubeUrl: 'https://www.youtube.com/watch?v=Tn6-PIqc4UM',
    spotifyUrl: 'https://open.spotify.com/track/3H7sjXgwmzwlt8C9HfTL2B',
  ),
  Song(
    title: 'Roar',
    artist: 'Katy Perry',
    youtubeUrl: 'https://www.youtube.com/watch?v=CevxZvSJLk8',
    spotifyUrl: 'https://open.spotify.com/track/6jHhuXbWx1XTnSDBK3z3ad',
  ),
  Song(
    title: 'Shut Up and Dance',
    artist: 'WALK THE MOON',
    youtubeUrl: 'https://www.youtube.com/watch?v=6JCLY0Rlx6Q',
    spotifyUrl: 'https://open.spotify.com/track/0fs9mOXkWgScM2XUp39FC7',
  ),
  Song(
    title: 'Just the Way You Are',
    artist: 'Bruno Mars',
    youtubeUrl: 'https://www.youtube.com/watch?v=LjhCEhWiKXk',
    spotifyUrl: 'https://open.spotify.com/track/0lwB57R1VhKjH1nsoCmVrc',
  ),
  Song(
    title: 'Sugar',
    artist: 'Maroon 5',
    youtubeUrl: 'https://www.youtube.com/watch?v=09R8_2nJtjg',
    spotifyUrl: 'https://open.spotify.com/track/3fM4J3P4U28p38Wkwy8k9J',
  ),
  Song(
    title: 'Firework',
    artist: 'Katy Perry',
    youtubeUrl: 'https://www.youtube.com/watch?v=QGJuMBdaqIw',
    spotifyUrl: 'https://open.spotify.com/track/4j6A8tAHXyHZKhbhmJlZxY',
  ),
  Song(
    title: 'Wake Me Up Before You Go-Go',
    artist: 'Wham!',
    youtubeUrl: 'https://www.youtube.com/watch?v=pIgZ7gMze7A',
    spotifyUrl: 'https://open.spotify.com/track/2l9q6DL3XlP6p5Nidqs9Am',
  ),
  Song(
    title: 'I Gotta Feeling',
    artist: 'The Black Eyed Peas',
    youtubeUrl: 'https://www.youtube.com/watch?v=uSD4vsh1zDA',
    spotifyUrl: 'https://open.spotify.com/track/2bXykLgIWKX43izxhE6h5t',
  ),
  Song(
    title: 'Dancing Queen',
    artist: 'ABBA',
    youtubeUrl: 'https://www.youtube.com/watch?v=xFrGuyw1V8s',
    spotifyUrl: 'https://open.spotify.com/track/1hKch1uhD4F2lGtt7EK9fl',
  ),
  Song(
    title: 'Can’t Stop the Feeling!',
    artist: 'Justin Timberlake',
    youtubeUrl: 'https://www.youtube.com/watch?v=ru0K8uYEZWw',
    spotifyUrl: 'https://open.spotify.com/track/7yOdUt4hzFzZySpj5vZPQg',
  ),
  Song(
    title: 'Don’t Stop Me Now',
    artist: 'Queen',
    youtubeUrl: 'https://www.youtube.com/watch?v=HgzGwKwLmgM',
    spotifyUrl: 'https://open.spotify.com/track/7r1a8ZgdjO3wWjswfthe9Z',
  ),
  Song(
    title: 'Take On Me',
    artist: 'a-ha',
    youtubeUrl: 'https://www.youtube.com/watch?v=djV11Xbc914',
    spotifyUrl: 'https://open.spotify.com/track/2ndzzlDkA5TQU5kqt4G8f0',
  ),
  Song(
    title: 'Happy Together',
    artist: 'The Turtles',
    youtubeUrl: 'https://www.youtube.com/watch?v=ZxVZYIsYZnM',
    spotifyUrl: 'https://open.spotify.com/track/7r71W02TtNzNdOTNzzXgYH',
  ),
  Song(
    title: 'Good Time',
    artist: 'Owl City & Carly Rae Jepsen',
    youtubeUrl: 'https://www.youtube.com/watch?v=H7S5qVf-V2I',
    spotifyUrl: 'https://open.spotify.com/track/5RpN8CV5LBqj8fAq8GmQUh',
  ),
  Song(
    title: 'I’m Yours',
    artist: 'Jason Mraz',
    youtubeUrl: 'https://www.youtube.com/watch?v=EkHTsc9PU2A',
    spotifyUrl: 'https://open.spotify.com/track/7iDpZGEnXvx72kgX2ycnF1',
  ),
  Song(
    title: 'Viva La Vida',
    artist: 'Coldplay',
    youtubeUrl: 'https://www.youtube.com/watch?v=dvgZkm1xWPE',
    spotifyUrl: 'https://open.spotify.com/track/4z2eTX22K2PzLqUdcQXJlA',
  ),
  Song(
    title: 'All Star',
    artist: 'Smash Mouth',
    youtubeUrl: 'https://www.youtube.com/watch?v=L_jWHffIx5E',
    spotifyUrl: 'https://open.spotify.com/track/7b8v9TX7Xzm8x2k5C1c9Sh',
  ),
  Song(
    title: 'Sweet Caroline',
    artist: 'Neil Diamond',
    youtubeUrl: 'https://www.youtube.com/watch?v=4m5NpSyd7k4',
    spotifyUrl: 'https://open.spotify.com/track/2t1l93eswXjXx5tLf1yY33',
  ),
  Song(
    title: 'September',
    artist: 'Earth, Wind & Fire',
    youtubeUrl: 'https://www.youtube.com/watch?v=Gs069dndIYk',
    spotifyUrl: 'https://open.spotify.com/track/1sM7f0w0ojgJrG7QHmy6QJ',
  ),Song(
    title: 'Shiny Happy People',
    artist: 'R.E.M.',
    youtubeUrl: 'https://www.youtube.com/watch?v=2kw6r9D6UGI',
    spotifyUrl: 'https://open.spotify.com/track/0gIiAOlIUSpglU9XN2Ff7R',
  ),
  Song(
    title: 'On Top of the World',
    artist: 'Imagine Dragons',
    youtubeUrl: 'https://www.youtube.com/watch?v=w5tWYmIpl94',
    spotifyUrl: 'https://open.spotify.com/track/0YfJOSQ9Tn9xhQ9I4iM8vj',
  ),
  Song(
    title: 'You Make My Dreams',
    artist: 'Hall & Oates',
    youtubeUrl: 'https://www.youtube.com/watch?v=EE2Q5J7cPRY',
    spotifyUrl: 'https://open.spotify.com/track/2qswUuCBgGg4iGVx5VHH9f',
  ),
  Song(
    title: 'Go Your Own Way',
    artist: 'Fleetwood Mac',
    youtubeUrl: 'https://www.youtube.com/watch?v=6ul-cZyuYq4',
    spotifyUrl: 'https://open.spotify.com/track/0uQsZ21ktVEMt8PQIZI9p9',
  ),
  Song(
    title: 'Best Day of My Life',
    artist: 'American Authors',
    youtubeUrl: 'https://www.youtube.com/watch?v=Y66j_BUC3L0',
    spotifyUrl: 'https://open.spotify.com/track/6mHkZgIE2bYr4WhgDHDYQ0',
  ),
  Song(
    title: 'It’s My Life',
    artist: 'Bon Jovi',
    youtubeUrl: 'https://www.youtube.com/watch?v=vx2u5uUu3DE',
    spotifyUrl: 'https://open.spotify.com/track/2VXYAWlQ6V7Vf2OqkFzS5b',
  ),
  Song(
    title: 'Counting Stars',
    artist: 'OneRepublic',
    youtubeUrl: 'https://www.youtube.com/watch?v=hT_nvWreIhg',
    spotifyUrl: 'https://open.spotify.com/track/3LhDg73FSdyosfgERmVqYg',
  ),
  Song(
    title: 'Fireflies',
    artist: 'Owl City',
    youtubeUrl: 'https://www.youtube.com/watch?v=psuRGfAaju4',
    spotifyUrl: 'https://open.spotify.com/track/7lXhDmtOSCSdVVAGvxYebB',
  ),
  Song(
    title: 'We Found Love',
    artist: 'Rihanna ft. Calvin Harris',
    youtubeUrl: 'https://www.youtube.com/watch?v=tg00YEETFzg',
    spotifyUrl: 'https://open.spotify.com/track/1vZukxeNSbqlGp3dLddtqG',
  ),
  Song(
    title: 'Walk Me Home',
    artist: 'P!nk',
    youtubeUrl: 'https://www.youtube.com/watch?v=MXkDh1QfwYw',
    spotifyUrl: 'https://open.spotify.com/track/3WkzqIu2wZQsG4SjqkNq2g',
  ),
  Song(
    title: 'Let’s Go',
    artist: 'Calvin Harris ft. Ne-Yo',
    youtubeUrl: 'https://www.youtube.com/watch?v=Q2tQ59hNqcI',
    spotifyUrl: 'https://open.spotify.com/track/6pwoxt4o2rf6BoIu90xlEd',
  ),

];


List<Song> playlistSad = [
  Song(
    title: 'Nothing Else Matters',
    artist: 'Metallica',
    youtubeUrl: 'https://www.youtube.com/watch?v=tAGnKpE4NCI',
    spotifyUrl: 'https://open.spotify.com/track/2F0QLv7tOswqrdO0B1uV2i',
  ),
  Song(
    title: 'Someone Like You',
    artist: 'Adele',
    youtubeUrl: 'https://www.youtube.com/watch?v=hLQl3WQQoQ0',
    spotifyUrl: 'https://open.spotify.com/track/1vAe6IFwpIf4N6gkrGmvYh',
  ),
  Song(
    title: 'The Night We Met',
    artist: 'Lord Huron',
    youtubeUrl: 'https://www.youtube.com/watch?v=2vMhYbE1kzE',
    spotifyUrl: 'https://open.spotify.com/track/3WuH28hTybVt5O0RzPT9fl',
  ),
  Song(
    title: 'Fix You',
    artist: 'Coldplay',
    youtubeUrl: 'https://www.youtube.com/watch?v=k4V3Mo61fJM',
    spotifyUrl: 'https://open.spotify.com/track/0kRgsFh5yHfKpDg7R52Ogw',
  ),
  Song(
    title: 'I Will Always Love You',
    artist: 'Whitney Houston',
    youtubeUrl: 'https://www.youtube.com/watch?v=3JWTaaS7LdU',
    spotifyUrl: 'https://open.spotify.com/track/3vDWBjK3AkV7cKZX5bm4yS',
  ),
  Song(
    title: 'Hurt',
    artist: 'Johnny Cash',
    youtubeUrl: 'https://www.youtube.com/watch?v=vt1Pwfnh5pc',
    spotifyUrl: 'https://open.spotify.com/track/1Lcn7T1I0adF9L7UfrT1Gg',
  ),
  Song(
    title: 'Tears in Heaven',
    artist: 'Eric Clapton',
    youtubeUrl: 'https://www.youtube.com/watch?v=JrdnjjpzDOw',
    spotifyUrl: 'https://open.spotify.com/track/2Me0HzJji9gqflGdr39jMw',
  ),
  Song(
    title: 'The A Team',
    artist: 'Ed Sheeran',
    youtubeUrl: 'https://www.youtube.com/watch?v=UWlZJo4gPj4',
    spotifyUrl: 'https://open.spotify.com/track/1TLKAX8vVj9u1QtbdrIIrF',
  ),
  Song(
    title: 'Creep',
    artist: 'Radiohead',
    youtubeUrl: 'https://www.youtube.com/watch?v=XF4w5ZLRwKM',
    spotifyUrl: 'https://open.spotify.com/track/3xRrb8ivhUo7JfQtfkO0gt',
  ),
  Song(
    title: 'All I Want',
    artist: 'Kodaline',
    youtubeUrl: 'https://www.youtube.com/watch?v=K5p8BzmzBdo',
    spotifyUrl: 'https://open.spotify.com/track/4ZZzZTOfVmctcBZlud5fF6',
  ),
  Song(
    title: 'I Will Remember You',
    artist: 'Sarah McLachlan',
    youtubeUrl: 'https://www.youtube.com/watch?v=8w3Nz0LqhdE',
    spotifyUrl: 'https://open.spotify.com/track/3CZ0lcs7dJjNCUp5ZT5g7h',
  ),
  Song(
    title: 'Let Her Go',
    artist: 'Passenger',
    youtubeUrl: 'https://www.youtube.com/watch?v=RBumgq5yVrA',
    spotifyUrl: 'https://open.spotify.com/track/4h4wKo13XTZVcswKq3vK5H',
  ),
  Song(
    title: 'The Scientist',
    artist: 'Coldplay',
    youtubeUrl: 'https://www.youtube.com/watch?v=RB-RcX5DS5I',
    spotifyUrl: 'https://open.spotify.com/track/2eIzc9ENtZYZXk6fcXqzLD',
  ),
  Song(
    title: 'Hallelujah',
    artist: 'Jeff Buckley',
    youtubeUrl: 'https://www.youtube.com/watch?v=y8AWFf7EAc4',
    spotifyUrl: 'https://open.spotify.com/track/3z2cc8pdz0xtXXsl8sVKZc',
  ),
  Song(
    title: 'Yesterday',
    artist: 'The Beatles',
    youtubeUrl: 'https://www.youtube.com/watch?v=NrgmTC6MjXk',
    spotifyUrl: 'https://open.spotify.com/track/6T0mLgekmTKedHGnPqODTz',
  ),
  Song(
    title: 'Black',
    artist: 'Pearl Jam',
    youtubeUrl: 'https://www.youtube.com/watch?v=ljSg2ZlOT7I',
    spotifyUrl: 'https://open.spotify.com/track/4xsmjjgtpfALowfgTSH8ac',
  ),
  Song(
    title: 'Tears Dry on Their Own',
    artist: 'Amy Winehouse',
    youtubeUrl: 'https://www.youtube.com/watch?v=2mEX1g6EF0A',
    spotifyUrl: 'https://open.spotify.com/track/0t2Psm5nIRKkaZG8O9KTNs',
  ),
  Song(
    title: 'Say Something',
    artist: 'A Great Big World ft. Christina Aguilera',
    youtubeUrl: 'https://www.youtube.com/watch?v=J9J2ojmOImo',
    spotifyUrl: 'https://open.spotify.com/track/5GhOG0yuwyA4sRLxlyGz4p',
  ),
  Song(
    title: 'My Immortal',
    artist: 'Evanescence',
    youtubeUrl: 'https://www.youtube.com/watch?v=5TqjZow0eq4',
    spotifyUrl: 'https://open.spotify.com/track/2OVh4FLKoGFkHahVw4pQbb',
  ),
  Song(
    title: 'Breathe Me',
    artist: 'Sia',
    youtubeUrl: 'https://www.youtube.com/watch?v=ghPcYnvAt9c',
    spotifyUrl: 'https://open.spotify.com/track/5yKq3r7g51fiK54hlHkflG',
  ),
  Song(
    title: 'I Don’t Want to Miss a Thing',
    artist: 'Aerosmith',
    youtubeUrl: 'https://www.youtube.com/watch?v=JkK8g6FMEXE',
    spotifyUrl: 'https://open.spotify.com/track/5oO0wD7pghT4VVFts5ct09',
  ),
  Song(
    title: 'The First Cut Is the Deepest',
    artist: 'Sheryl Crow',
    youtubeUrl: 'https://www.youtube.com/watch?v=PCv0tLLoq5I',
    spotifyUrl: 'https://open.spotify.com/track/3eTwxgOlg2oBBgLMTsm6mT',
  ),
  Song(
    title: 'Sad Song',
    artist: 'We The Kings',
    youtubeUrl: 'https://www.youtube.com/watch?v=gZxlQQ_3PaM',
    spotifyUrl: 'https://open.spotify.com/track/4FbLlkbs73IjeLjiI1Qrxr',
  ),
  Song(
    title: 'If I Ain’t Got You',
    artist: 'Alicia Keys',
    youtubeUrl: 'https://www.youtube.com/watch?v=Ju8Hr50Ckwk',
    spotifyUrl: 'https://open.spotify.com/track/5xW0wfxl7d8c6n5ZzEewLR',
  ),
  Song(
    title: 'Back to December',
    artist: 'Taylor Swift',
    youtubeUrl: 'https://www.youtube.com/watch?v=8Y0i2EKllEw',
    spotifyUrl: 'https://open.spotify.com/track/2E1LTVhpIjgUhcAGhIuY2Q',
  ),
  Song(
    title: 'Un-break My Heart',
    artist: 'Toni Braxton',
    youtubeUrl: 'https://www.youtube.com/watch?v=p2Rch6WvTjI',
    spotifyUrl: 'https://open.spotify.com/track/3eZ4eLzqtwuaYwdzD34rK1',
  ),
  Song(
    title: 'I’m Not the Only One',
    artist: 'Sam Smith',
    youtubeUrl: 'https://www.youtube.com/watch?v=pB-5XG-DbAA',
    spotifyUrl: 'https://open.spotify.com/track/3z4FqNEoMQfqUt6Y7L7Gn4',
  ),
  Song(
    title: 'Skinny Love',
    artist: 'Bon Iver',
    youtubeUrl: 'https://www.youtube.com/watch?v=ssdgFoHLwnk',
    spotifyUrl: 'https://open.spotify.com/track/7CjF7taV6NDoIaWSmsuF4Y',
  ),
];


List<Song> playlistRelaxed = [
  Song(
    title: 'Banana Pancakes',
    artist: 'Jack Johnson',
    youtubeUrl: 'https://www.youtube.com/watch?v=5pGoAC5nO_g',
    spotifyUrl: 'https://open.spotify.com/track/7Fx0SkMofDEpkNkMB4Jbdn',
  ),
  Song(
    title: 'Come Away With Me',
    artist: 'Norah Jones',
    youtubeUrl: 'https://www.youtube.com/watch?v=lg9sHPm7B14',
    spotifyUrl: 'https://open.spotify.com/track/6ImswBO9gzRzZ7GR3W9A6O',
  ),
  Song(
    title: 'Sunset Lover',
    artist: 'Petit Biscuit',
    youtubeUrl: 'https://www.youtube.com/watch?v=zx69h4p0Z40',
    spotifyUrl: 'https://open.spotify.com/track/2v6BzpVG2z1l3V7Qjyy0or',
  ),
  Song(
    title: 'Better Together',
    artist: 'Jack Johnson',
    youtubeUrl: 'https://www.youtube.com/watch?v=0eG5OhTe60g',
    spotifyUrl: 'https://open.spotify.com/track/4gXNpa8yI5IM5YmOxIBIUt',
  ),
  Song(
    title: 'The Ocean',
    artist: 'Mike Perry ft. Shy Martin',
    youtubeUrl: 'https://www.youtube.com/watch?v=zn2K9_Fu6PM',
    spotifyUrl: 'https://open.spotify.com/track/3uy4VeGfOjxxrf4mxXzGbf',
  ),
  Song(
    title: 'Gravity',
    artist: 'John Mayer',
    youtubeUrl: 'https://www.youtube.com/watch?v=JwFz0lrS_f4',
    spotifyUrl: 'https://open.spotify.com/track/47Yz6l9B8pr5GlzF5Y3DNw',
  ),
  Song(
    title: 'Breezeblocks',
    artist: 'alt-J',
    youtubeUrl: 'https://www.youtube.com/watch?v=rVeMiVU77wo',
    spotifyUrl: 'https://open.spotify.com/track/2vYY2JeDBrQdT07g8epq2C',
  ),
  Song(
    title: 'Lost in Japan',
    artist: 'Shawn Mendes',
    youtubeUrl: 'https://www.youtube.com/watch?v=tlHkSByFy5w',
    spotifyUrl: 'https://open.spotify.com/track/3jfm25zTHJNh8VGJfsEXc5',
  ),
  Song(
    title: 'Home',
    artist: 'Edward Sharpe & The Magnetic Zeros',
    youtubeUrl: 'https://www.youtube.com/watch?v=DHEOF_rcND8',
    spotifyUrl: 'https://open.spotify.com/track/0TtzDKw2MiZuE6OXB93VZ0',
  ),
  Song(
    title: 'Coffee',
    artist: 'Sylvan Esso',
    youtubeUrl: 'https://www.youtube.com/watch?v=6PYUB3hGJks',
    spotifyUrl: 'https://open.spotify.com/track/5a80yImKpOhKddqkT9Q7bs',
  ),
  Song(
    title: 'Tenerife Sea',
    artist: 'Ed Sheeran',
    youtubeUrl: 'https://www.youtube.com/watch?v=CTkZj9w2GGw',
    spotifyUrl: 'https://open.spotify.com/track/7vpa43cbTuAhtBa2X9lCcp',
  ),
  Song(
    title: 'Ain’t No Sunshine',
    artist: 'Bill Withers',
    youtubeUrl: 'https://www.youtube.com/watch?v=tIdIqbv7SPo',
    spotifyUrl: 'https://open.spotify.com/track/0nhJ4qVw1zXfTRv0mQ9fl7',
  ),
  Song(
    title: 'Ocean Eyes',
    artist: 'Billie Eilish',
    youtubeUrl: 'https://www.youtube.com/watch?v=viimfQi_pUw',
    spotifyUrl: 'https://open.spotify.com/track/5nMF3QI4ch1FqbwEIS5i9l',
  ),
  Song(
    title: 'Dreams',
    artist: 'Fleetwood Mac',
    youtubeUrl: 'https://www.youtube.com/watch?v=mrZRURcb1cM',
    spotifyUrl: 'https://open.spotify.com/track/3NKlRHTk27z5VhYw4pje8v',
  ),
  Song(
    title: 'Slow Dancing in a Burning Room',
    artist: 'John Mayer',
    youtubeUrl: 'https://www.youtube.com/watch?v=9r5L95n9mMY',
    spotifyUrl: 'https://open.spotify.com/track/2Fw9v8F0S7J0xlr7YhFmkp',
  ),
  Song(
    title: 'Budapest',
    artist: 'George Ezra',
    youtubeUrl: 'https://www.youtube.com/watch?v=VHrLPs3_1fU',
    spotifyUrl: 'https://open.spotify.com/track/4kJNxa82wnaPpyusfv5fbH',
  ),
  Song(
    title: 'Riptide',
    artist: 'Vance Joy',
    youtubeUrl: 'https://www.youtube.com/watch?v=uJ_1HMAGb4k',
    spotifyUrl: 'https://open.spotify.com/track/1rFOU7WhxvJfjywXPYHLjo',
  ),
  Song(
    title: 'Falling Slowly',
    artist: 'Glen Hansard & Marketa Irglova',
    youtubeUrl: 'https://www.youtube.com/watch?v=SwVqaym4DlM',
    spotifyUrl: 'https://open.spotify.com/track/7k55yCwTSkBZiODX9GSm6X',
  ),
  Song(
    title: 'Stay With Me',
    artist: 'Sam Smith',
    youtubeUrl: 'https://www.youtube.com/watch?v=pB-5XG-DbAA',
    spotifyUrl: 'https://open.spotify.com/track/7xKsbD2t9Vq9BlTlAxFznF',
  ),
  Song(
    title: 'Landslide',
    artist: 'Fleetwood Mac',
    youtubeUrl: 'https://www.youtube.com/watch?v=V8f8fgm1n9g',
    spotifyUrl: 'https://open.spotify.com/track/0oGAw7kvDPzE21kz2H9z8T',
  ),
  Song(
    title: 'Yellow',
    artist: 'Coldplay',
    youtubeUrl: 'https://www.youtube.com/watch?v=yKNxeF4KMsY',
    spotifyUrl: 'https://open.spotify.com/track/4kJlJ4FfL5vHUMRctRCSGy',
  ),
  Song(
    title: 'Lost Cause',
    artist: 'Billie Eilish',
    youtubeUrl: 'https://www.youtube.com/watch?v=DiRkRttRRGk',
    spotifyUrl: 'https://open.spotify.com/track/3Adf5j31aZfwZ7ygkLvHxr',
  ),
];

List<Song> playlistEnergetic = [
  Song(
    title: 'Uptown Funk',
    artist: 'Mark Ronson ft. Bruno Mars',
    youtubeUrl: 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
    spotifyUrl: 'https://open.spotify.com/track/0fFTr7XkjWwAqR4Erswfjh',
  ),
  Song(
    title: 'Can’t Stop the Feeling!',
    artist: 'Justin Timberlake',
    youtubeUrl: 'https://www.youtube.com/watch?v=ru0K8uYEZWw',
    spotifyUrl: 'https://open.spotify.com/track/7zcfTGv6hY9D9wZ7jZ41R6',
  ),
  Song(
    title: 'Shake It Off',
    artist: 'Taylor Swift',
    youtubeUrl: 'https://www.youtube.com/watch?v=nfWlot6h_JM',
    spotifyUrl: 'https://open.spotify.com/track/0bC42uZa02k0NNfOwTYOge',
  ),
  Song(
    title: 'Levitating',
    artist: 'Dua Lipa ft. DaBaby',
    youtubeUrl: 'https://www.youtube.com/watch?v=TUVcZfQe-Kw',
    spotifyUrl: 'https://open.spotify.com/track/5ZIGkKN7L3NKNm7h4y0EuC',
  ),
  Song(
    title: 'Feel It Still',
    artist: 'Portugal. The Man',
    youtubeUrl: 'https://www.youtube.com/watch?v=ih8npDniJ6g',
    spotifyUrl: 'https://open.spotify.com/track/0JfK2eC7r0U0K2eM9vH6mG',
  ),
  Song(
    title: 'Titanium',
    artist: 'David Guetta ft. Sia',
    youtubeUrl: 'https://www.youtube.com/watch?v=JRfuAukYTKg',
    spotifyUrl: 'https://open.spotify.com/track/3H7pV7M2wLMsFe32tRai5Y',
  ),
  Song(
    title: 'Don’t Start Now',
    artist: 'Dua Lipa',
    youtubeUrl: 'https://www.youtube.com/watch?v=oygrmJFKYlY',
    spotifyUrl: 'https://open.spotify.com/track/0GgGvgyO7IOrbaQFknwypB',
  ),
  Song(
    title: 'Party Rock Anthem',
    artist: 'LMFAO',
    youtubeUrl: 'https://www.youtube.com/watch?v=KQ6zr6kCPj8',
    spotifyUrl: 'https://open.spotify.com/track/6gCHQ0Qhfi9VxStH2jPdu5',
  ),
  Song(
    title: 'Bang Bang',
    artist: 'Jessie J, Ariana Grande, Nicki Minaj',
    youtubeUrl: 'https://www.youtube.com/watch?v=0HDdjfZxX7o',
    spotifyUrl: 'https://open.spotify.com/track/2bq2zpHfghQ9fMJ5FA2Olz',
  ),
  Song(
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    youtubeUrl: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
    spotifyUrl: 'https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b',
  ),
  Song(
    title: 'Hips Don’t Lie',
    artist: 'Shakira ft. Wyclef Jean',
    youtubeUrl: 'https://www.youtube.com/watch?v=DUT5rEU6pqM',
    spotifyUrl: 'https://open.spotify.com/track/3jFrk9Gg5wK5ITwYZpa7Pr',
  ),
  Song(
    title: 'Stronger',
    artist: 'Kanye West',
    youtubeUrl: 'https://www.youtube.com/watch?v=PsO6ZnUZI0g',
    spotifyUrl: 'https://open.spotify.com/track/3j6wVqgVFbJUpjpwsO3U6V',
  ),
  Song(
    title: 'Waka Waka (This Time for Africa)',
    artist: 'Shakira ft. Freshlyground',
    youtubeUrl: 'https://www.youtube.com/watch?v=pRpeEdMmmQ0',
    spotifyUrl: 'https://open.spotify.com/track/2TZw9k48N1Jvl2nkhXmDsV',
  ),
  Song(
    title: 'Scream & Shout',
    artist: 'will.i.am ft. Britney Spears',
    youtubeUrl: 'https://www.youtube.com/watch?v=9t0qHEaa4yI',
    spotifyUrl: 'https://open.spotify.com/track/0uvvRgtDPFT16rgByx4jET',
  ),
  Song(
    title: 'On The Floor',
    artist: 'Jennifer Lopez ft. Pitbull',
    youtubeUrl: 'https://www.youtube.com/watch?v=t4H_Zoh7G5A',
    spotifyUrl: 'https://open.spotify.com/track/7tV2RUz5jfws21u8Y8Qdfk',
  ),
  Song(
    title: 'Rock Your Body',
    artist: 'Justin Timberlake',
    youtubeUrl: 'https://www.youtube.com/watch?v=TSVHoHyErRk',
    spotifyUrl: 'https://open.spotify.com/track/4Yb9jCZrpzOzzxgY7ytH9S',
  ),
  Song(
    title: 'I Gotta Feeling',
    artist: 'The Black Eyed Peas',
    youtubeUrl: 'https://www.youtube.com/watch?v=uSD4vsh1zDA',
    spotifyUrl: 'https://open.spotify.com/track/6H9qYrJt0PxxkFmEw6yRQQ',
  ),
  Song(
    title: 'Shut Up and Dance',
    artist: 'WALK THE MOON',
    youtubeUrl: 'https://www.youtube.com/watch?v=6JCLY0Rlx6Q',
    spotifyUrl: 'https://open.spotify.com/track/5xx2p7jJ7y5gqMBgX2MQmi',
  ),
  Song(
    title: 'Let’s Go',
    artist: 'Ne-Yo ft. Calvin Harris',
    youtubeUrl: 'https://www.youtube.com/watch?v=EuaKkfiXXhw',
    spotifyUrl: 'https://open.spotify.com/track/6z6AqFAh77V7FzMzM7Axqp',
  ),
  Song(
    title: 'Alive',
    artist: 'Sia',
    youtubeUrl: 'https://www.youtube.com/watch?v=MJkZ1I9vXoI',
    spotifyUrl: 'https://open.spotify.com/track/7yCPwM0AwhQw57Jw6g7WBr',
  ),
  Song(
    title: 'Good as Hell',
    artist: 'Lizzo',
    youtubeUrl: 'https://www.youtube.com/watch?v=4zGFDxkgApY',
    spotifyUrl: 'https://open.spotify.com/track/2t7jp7wK1cIDEX6rD5ZnFh',
  ),
];

List<Song> playlistMotivated = [
  Song(
    title: 'Eye of the Tiger',
    artist: 'Survivor',
    youtubeUrl: 'https://www.youtube.com/watch?v=btPJPFnesV4',
    spotifyUrl: 'https://open.spotify.com/track/3t3YbKXBhEMdY7z5DAZXyG',
  ),
  Song(
    title: 'Stronger',
    artist: 'Kanye West',
    youtubeUrl: 'https://www.youtube.com/watch?v=PsO6ZnUZI0g',
    spotifyUrl: 'https://open.spotify.com/track/3j6wVqgVFbJUpjpwsO3U6V',
  ),
  Song(
    title: 'Lose Yourself',
    artist: 'Eminem',
    youtubeUrl: 'https://www.youtube.com/watch?v=_Yhyp-_hX2s',
    spotifyUrl: 'https://open.spotify.com/track/1j1bNhMGsGmcoZZmhT60sT',
  ),
  Song(
    title: 'Happy',
    artist: 'Pharrell Williams',
    youtubeUrl: 'https://www.youtube.com/watch?v=ZbZSe6N_BXs',
    spotifyUrl: 'https://open.spotify.com/track/0lXf9IMJdEdvDygbaAzb5g',
  ),
  Song(
    title: 'Don’t Stop Believin’',
    artist: 'Journey',
    youtubeUrl: 'https://www.youtube.com/watch?v=1k8craCGpgs',
    spotifyUrl: 'https://open.spotify.com/track/0P7g61K3zPAI1CeqR5hfnk',
  ),
  Song(
    title: 'Firework',
    artist: 'Katy Perry',
    youtubeUrl: 'https://www.youtube.com/watch?v=QGJuMBdaqIw',
    spotifyUrl: 'https://open.spotify.com/track/0QgyjoXM1zjdyWddqqsQnd',
  ),
  Song(
    title: 'Till I Collapse',
    artist: 'Eminem ft. Nate Dogg',
    youtubeUrl: 'https://www.youtube.com/watch?v=ytQ5C4K7pHk',
    spotifyUrl: 'https://open.spotify.com/track/4FhHToZyxsSkGmjVFSyFSJ',
  ),
  Song(
    title: 'On Top of the World',
    artist: 'Imagine Dragons',
    youtubeUrl: 'https://www.youtube.com/watch?v=w5tWYmIOWGk',
    spotifyUrl: 'https://open.spotify.com/track/1j0Zo8sMRZTJ3B5w91dwQk',
  ),
  Song(
    title: 'We Will Rock You',
    artist: 'Queen',
    youtubeUrl: 'https://www.youtube.com/watch?v=-tJYN-eG1l0',
    spotifyUrl: 'https://open.spotify.com/track/0yJEQJ4GHJ9pAGzYYWLcew',
  ),
  Song(
    title: 'Stronger (What Doesn’t Kill You)',
    artist: 'Kelly Clarkson',
    youtubeUrl: 'https://www.youtube.com/watch?v=Xn676-fLq7I',
    spotifyUrl: 'https://open.spotify.com/track/33AD8wPfD9SjiqUYPBxv2P',
  ),
  Song(
    title: 'Fighter',
    artist: 'Christina Aguilera',
    youtubeUrl: 'https://www.youtube.com/watch?v=QCT1t_gwOHY',
    spotifyUrl: 'https://open.spotify.com/track/1XqE2XvqQJltyW4R8hb7Mt',
  ),
  Song(
    title: 'The Champion',
    artist: 'Carrie Underwood ft. Ludacris',
    youtubeUrl: 'https://www.youtube.com/watch?v=5d3XJk9I5MI',
    spotifyUrl: 'https://open.spotify.com/track/3oiRzXGZjkZhsXvhHctuDN',
  ),
  Song(
    title: 'Rise Up',
    artist: 'Andra Day',
    youtubeUrl: 'https://www.youtube.com/watch?v=lwgr_IMeEgA',
    spotifyUrl: 'https://open.spotify.com/track/4kL0zHgFwswCSyztEFjIN9',
  ),
  Song(
    title: 'Power',
    artist: 'Kanye West',
    youtubeUrl: 'https://www.youtube.com/watch?v=R8H3uXf8gqI',
    spotifyUrl: 'https://open.spotify.com/track/1uyP9cAV2wBfXceGJxXK2v',
  ),
  Song(
    title: 'Waka Waka (This Time for Africa)',
    artist: 'Shakira ft. Freshlyground',
    youtubeUrl: 'https://www.youtube.com/watch?v=pRpeEdMmmQ0',
    spotifyUrl: 'https://open.spotify.com/track/2TZw9k48N1Jvl2nkhXmDsV',
  ),
  Song(
    title: 'Unstoppable',
    artist: 'Sia',
    youtubeUrl: 'https://www.youtube.com/watch?v=YQHsXMglC9A',
    spotifyUrl: 'https://open.spotify.com/track/2b8X7pmDSoIR0eQI6Eu03s',
  ),
  Song(
    title: 'The Climb',
    artist: 'Miley Cyrus',
    youtubeUrl: 'https://www.youtube.com/watch?v=NG2zI3JzYkM',
    spotifyUrl: 'https://open.spotify.com/track/1D1oLceTrb5FGo1gN1vYnp',
  ),
  Song(
    title: 'Run the World (Girls)',
    artist: 'Beyoncé',
    youtubeUrl: 'https://www.youtube.com/watch?v=VBmCJEehYtU',
    spotifyUrl: 'https://open.spotify.com/track/1wX53tvSyjEgoNEjFcsK9y',
  ),
  Song(
    title: 'Good Feeling',
    artist: 'Flo Rida',
    youtubeUrl: 'https://www.youtube.com/watch?v=3OnnDqH6Wj8',
    spotifyUrl: 'https://open.spotify.com/track/3n39w2m8OjMIHDpoI7FhhA',
  ),
  Song(
    title: 'Survivor',
    artist: 'Destiny’s Child',
    youtubeUrl: 'https://www.youtube.com/watch?v=Wmc8bQoL-J0',
    spotifyUrl: 'https://open.spotify.com/track/3E1jpOflxwq3bJUmgtpwnu',
  ),
  Song(
    title: 'Victory',
    artist: 'Puff Daddy ft. The Notorious B.I.G. & Busta Rhymes',
    youtubeUrl: 'https://www.youtube.com/watch?v=q2Le6A34jxI',
    spotifyUrl: 'https://open.spotify.com/track/5Qe9J27W6xEV9QThH0pKv2',
  ),
];

List<Song> playlistStressed = [
  Song(
    title: 'Under Pressure',
    artist: 'Queen & David Bowie',
    youtubeUrl: 'https://www.youtube.com/watch?v=a01QQZyl-_I',
    spotifyUrl: 'https://open.spotify.com/track/3IF9D75ro6eDmc4GZTcnKZ',
  ),
  Song(
    title: 'Mad World',
    artist: 'Gary Jules',
    youtubeUrl: 'https://www.youtube.com/watch?v=4N3N1MlvVc4',
    spotifyUrl: 'https://open.spotify.com/track/2QdMnQrsddSoI94HgyQxXZ',
  ),
  Song(
    title: 'Breathe',
    artist: 'The Prodigy',
    youtubeUrl: 'https://www.youtube.com/watch?v=1d6YoNnq6zI',
    spotifyUrl: 'https://open.spotify.com/track/6gUuNRL9rx3ErS6wsm5yDt',
  ),
  Song(
    title: 'Stress',
    artist: 'Justice',
    youtubeUrl: 'https://www.youtube.com/watch?v=FvD0Lgk_KiM',
    spotifyUrl: 'https://open.spotify.com/track/5c2Hhf9bs2xDjaFcgt6phL',
  ),
  Song(
    title: 'The Way I Am',
    artist: 'Eminem',
    youtubeUrl: 'https://www.youtube.com/watch?v=4hD3APn5y6E',
    spotifyUrl: 'https://open.spotify.com/track/5HLNcThhf6jcgw7urq9nQ3',
  ),
  Song(
    title: 'Numb',
    artist: 'Linkin Park',
    youtubeUrl: 'https://www.youtube.com/watch?v=kXYiU_JCYtU',
    spotifyUrl: 'https://open.spotify.com/track/3Xi9fugPbJczlSfxg9m8gh',
  ),
  Song(
    title: 'Tired',
    artist: 'Alan Walker',
    youtubeUrl: 'https://www.youtube.com/watch?v=AtNdFDmoR9s',
    spotifyUrl: 'https://open.spotify.com/track/5oDCKe2s84f4q9coYgt1Ut',
  ),
  Song(
    title: 'Waiting for Love',
    artist: 'Avicii',
    youtubeUrl: 'https://www.youtube.com/watch?v=Qv6p9W7ED-Y',
    spotifyUrl: 'https://open.spotify.com/track/0gIuZHgGsU5jx1sO7nvf75',
  ),
  Song(
    title: 'How to Save a Life',
    artist: 'The Fray',
    youtubeUrl: 'https://www.youtube.com/watch?v=cjVQ36NhbMk',
    spotifyUrl: 'https://open.spotify.com/track/1J6w04P0u2z9H9Oqj5Bfdy',
  ),
  Song(
    title: 'Breakdown',
    artist: 'Tantric',
    youtubeUrl: 'https://www.youtube.com/watch?v=a3B6bOVHbTY',
    spotifyUrl: 'https://open.spotify.com/track/3pK7g9i4Hh8E4g9grhStTI',
  ),
  Song(
    title: 'The Kill (Bury Me)',
    artist: '30 Seconds to Mars',
    youtubeUrl: 'https://www.youtube.com/watch?v=8yvVbMEno6g',
    spotifyUrl: 'https://open.spotify.com/track/0duT8sHeSp2m8BskYYF8l9',
  ),
  Song(
    title: 'In the End',
    artist: 'Linkin Park',
    youtubeUrl: 'https://www.youtube.com/watch?v=eVTXPUF4Oz4',
    spotifyUrl: 'https://open.spotify.com/track/1B3SZkpDXrsB6qZPfxOtO2',
  ),
  Song(
    title: 'Boulevard of Broken Dreams',
    artist: 'Green Day',
    youtubeUrl: 'https://www.youtube.com/watch?v=Soa3gO7tL-c',
    spotifyUrl: 'https://open.spotify.com/track/4dd2bfZIjvVtkaztA4SkzL',
  ),
  Song(
    title: 'I’m Not the Only One',
    artist: 'Sam Smith',
    youtubeUrl: 'https://www.youtube.com/watch?v=Jp-2cJ1sB60',
    spotifyUrl: 'https://open.spotify.com/track/1y8fjQal9ZGRSyfghw3w4v',
  ),
  Song(
    title: 'Everybody Hurts',
    artist: 'R.E.M.',
    youtubeUrl: 'https://www.youtube.com/watch?v=3wZbgs82yB4',
    spotifyUrl: 'https://open.spotify.com/track/6Swa5K2bmtEw1v7Fc3hFgo',
  ),
  Song(
    title: 'Hurt',
    artist: 'Nine Inch Nails',
    youtubeUrl: 'https://www.youtube.com/watch?v=odFlnqD5eL8',
    spotifyUrl: 'https://open.spotify.com/track/2tRVt2iXgP9M6TxnpDBx0h',
  ),
  Song(
    title: 'It’s My Life',
    artist: 'Bon Jovi',
    youtubeUrl: 'https://www.youtube.com/watch?v=Z2nGpNnzCD8',
    spotifyUrl: 'https://open.spotify.com/track/4lCwp9CSoHKg0QDRaCbaPp',
  ),
  Song(
    title: 'Pain',
    artist: 'Three Days Grace',
    youtubeUrl: 'https://www.youtube.com/watch?v=TDX7pvFHZbY',
    spotifyUrl: 'https://open.spotify.com/track/2nBznj5VpxVtlj4uaWsKY9',
  ),
  Song(
    title: 'Everything You Want',
    artist: 'Vertical Horizon',
    youtubeUrl: 'https://www.youtube.com/watch?v=6f2KFFu6i9o',
    spotifyUrl: 'https://open.spotify.com/track/47ApQsMlVgTWBt2cWv8Z4G',
  ),
  Song(
    title: 'Toxic',
    artist: 'Britney Spears',
    youtubeUrl: 'https://www.youtube.com/watch?v=LOZuxwVk7TU',
    spotifyUrl: 'https://open.spotify.com/track/1nFhKKiYmMRA9xBwvKOYg9',
  ),
];

List<Song> playlistNostalgic = [
  Song(
    title: 'Summer of 69',
    artist: 'Bryan Adams',
    youtubeUrl: 'https://www.youtube.com/watch?v=9fNwI5wmtS4',
    spotifyUrl: 'https://open.spotify.com/track/5ytOj8qzQ7v3GEoGYNK5q8',
  ),
  Song(
    title: 'Sweet Child O\' Mine',
    artist: 'Guns N\' Roses',
    youtubeUrl: 'https://www.youtube.com/watch?v=1w7OgIMMRc4',
    spotifyUrl: 'https://open.spotify.com/track/5vvaNxkQmU1EB50jIsftgh',
  ),
  Song(
    title: 'I Want It That Way',
    artist: 'Backstreet Boys',
    youtubeUrl: 'https://www.youtube.com/watch?v=4fndeDfaWCg',
    spotifyUrl: 'https://open.spotify.com/track/3Ne6u9hnvjdUEKnYex0rb0',
  ),
  Song(
    title: 'I\'ll Be There for You',
    artist: 'The Rembrandts',
    youtubeUrl: 'https://www.youtube.com/watch?v=Y7h2bYXLKHA',
    spotifyUrl: 'https://open.spotify.com/track/3bjm1U2L6mdz6FLp8IbsEx',
  ),
  Song(
    title: 'No Scrubs',
    artist: 'TLC',
    youtubeUrl: 'https://www.youtube.com/watch?v=FrLequ6dUdM',
    spotifyUrl: 'https://open.spotify.com/track/4Kv1rwJ73sEMf7d8XUwlTV',
  ),
  Song(
    title: 'Mr. Brightside',
    artist: 'The Killers',
    youtubeUrl: 'https://www.youtube.com/watch?v=gGdGFtwCNBE',
    spotifyUrl: 'https://open.spotify.com/track/5JqGRtTw1QyC0s5WpxEzeb',
  ),
  Song(
    title: 'Wannabe',
    artist: 'Spice Girls',
    youtubeUrl: 'https://www.youtube.com/watch?v=gJLIiF15oY8',
    spotifyUrl: 'https://open.spotify.com/track/6u4O96V63bmXGxaFJ9RL4P',
  ),
  Song(
    title: 'Take On Me',
    artist: 'A-ha',
    youtubeUrl: 'https://www.youtube.com/watch?v=djV11Xbc914',
    spotifyUrl: 'https://open.spotify.com/track/2Ihh62bwsFPOXYRPqWBKFc',
  ),
  Song(
    title: 'Africa',
    artist: 'Toto',
    youtubeUrl: 'https://www.youtube.com/watch?v=FTQbiNvZqaY',
    spotifyUrl: 'https://open.spotify.com/track/0m6kcdDktbGJSd5mWm3rxI',
  ),
  Song(
    title: 'Don\'t Stop Believin\'',
    artist: 'Journey',
    youtubeUrl: 'https://www.youtube.com/watch?v=1k8craCGpgs',
    spotifyUrl: 'https://open.spotify.com/track/4YzpYFw7FZYev4jO3cI3Ba',
  ),
  Song(
    title: 'Kiss Me',
    artist: 'Sixpence None the Richer',
    youtubeUrl: 'https://www.youtube.com/watch?v=5J49WG7SGBY',
    spotifyUrl: 'https://open.spotify.com/track/7f8w6PjTjl8eG7mH1c7xoD',
  ),
  Song(
    title: 'Torn',
    artist: 'Natalie Imbruglia',
    youtubeUrl: 'https://www.youtube.com/watch?v=eW5xC7K2f48',
    spotifyUrl: 'https://open.spotify.com/track/0uZlMJWZm90VAO3lYufZ3M',
  ),
  Song(
    title: "Everybody (Backstreet's Back)",
    artist: 'Backstreet Boys',
    youtubeUrl: 'https://www.youtube.com/watch?v=6M6samPEmp8',
    spotifyUrl: 'https://open.spotify.com/track/3t4rJz7dACZ8R78esQjc8m',
  ),
  Song(
    title: 'Take Me Home, Country Roads',
    artist: 'John Denver',
    youtubeUrl: 'https://www.youtube.com/watch?v=1vrEljMfXYo',
    spotifyUrl: 'https://open.spotify.com/track/4Ahlxu40Dk1DpUMnyv6bNR',
  ),
  Song(
    title: 'Dancing Queen',
    artist: 'ABBA',
    youtubeUrl: 'https://www.youtube.com/watch?v=xFrGuyw1V8s',
    spotifyUrl: 'https://open.spotify.com/track/3PnUvTkqVsI9WfA8Qpbe7t',
  ),
  Song(
    title: 'My Girl',
    artist: 'The Temptations',
    youtubeUrl: 'https://www.youtube.com/watch?v=6IUG-9jZD-g',
    spotifyUrl: 'https://open.spotify.com/track/6bZfSHD0nF0l0Y8cXLmr5u',
  ),
  Song(
    title: 'Yesterday',
    artist: 'The Beatles',
    youtubeUrl: 'https://www.youtube.com/watch?v=NrgmTC6MjXk',
    spotifyUrl: 'https://open.spotify.com/track/6T0mLgekmTKedHGnPqODTz',
  ),
  Song(
    title: 'Stayin' + 'Alive',
    artist: 'Bee Gees',
    youtubeUrl: 'https://www.youtube.com/watch?v=I_izvAbhExY',
    spotifyUrl: 'https://open.spotify.com/track/0m7XGBwct4Iqv4Vuw7m13p',
  ),
  Song(
    title: 'I Will Survive',
    artist: 'Gloria Gaynor',
    youtubeUrl: 'https://www.youtube.com/watch?v=ZBR2G-iI3-I',
    spotifyUrl: 'https://open.spotify.com/track/3otN2aLwp8J0fKxwVLe93r',
  ),
  Song(
    title: 'Imagine',
    artist: 'John Lennon',
    youtubeUrl: 'https://www.youtube.com/watch?v=YkgkThdzX-8',
    spotifyUrl: 'https://open.spotify.com/track/7yO3Qig0pLDVEfLPAldLxH',
  ),
  Song(
    title: 'The Fresh Prince of Bel-Air Theme Song',
    artist: 'DJ Jazzy Jeff & The Fresh Prince',
    youtubeUrl: 'https://www.youtube.com/watch?v=2vMtLJZBaEo',
    spotifyUrl: 'https://open.spotify.com/track/0tMvL17vZrxj3Re5jpM6kp',
  ),
];

List<Song> playlistFocused = [
  Song(
    title: 'Weightless',
    artist: 'Marconi Union',
    youtubeUrl: 'https://www.youtube.com/watch?v=UfcAVejslrU',
    spotifyUrl: 'https://open.spotify.com/track/2YbE7KUG9QJ7zHfHZNGc7b',
  ),
  Song(
    title: 'Clair de Lune',
    artist: 'Claude Debussy',
    youtubeUrl: 'https://www.youtube.com/watch?v=CvFH_6DNRCY',
    spotifyUrl: 'https://open.spotify.com/track/2kqqYwtD3fJfW2fyJt2Gq8',
  ),
  Song(
    title: 'Intro',
    artist: 'The XX',
    youtubeUrl: 'https://www.youtube.com/watch?v=0l_gC8Swn64',
    spotifyUrl: 'https://open.spotify.com/track/0QVeMtbYpWTb7yRmNj6UHg',
  ),
  Song(
    title: 'Sunset Lover',
    artist: 'Petit Biscuit',
    youtubeUrl: 'https://www.youtube.com/watch?v=7CIf6d2gU58',
    spotifyUrl: 'https://open.spotify.com/track/1CkbsID3l5AMJtFYVe7yRI',
  ),
  Song(
    title: 'Night Owl',
    artist: 'Galimatias',
    youtubeUrl: 'https://www.youtube.com/watch?v=ej7bRpV0IM4',
    spotifyUrl: 'https://open.spotify.com/track/6zvFCxwQYvmtb8omMmGVg0',
  ),
  Song(
    title: 'The Sound of Silence',
    artist: 'Simon & Garfunkel',
    youtubeUrl: 'https://www.youtube.com/watch?v=4fWyzwo1xg0',
    spotifyUrl: 'https://open.spotify.com/track/1DgA3DoPlgMCirnPuvpZxu',
  ),
  Song(
    title: 'Breathe',
    artist: 'The Prodigy',
    youtubeUrl: 'https://www.youtube.com/watch?v=NVd0NtmMd6M',
    spotifyUrl: 'https://open.spotify.com/track/5Ujfma1A2SYt5RAzSMdJ6B',
  ),
  Song(
    title: 'Electric Feel',
    artist: 'MGMT',
    youtubeUrl: 'https://www.youtube.com/watch?v=MmZexg8sXYk',
    spotifyUrl: 'https://open.spotify.com/track/2cLx7Vg0CvO9rWfS9bSQwD',
  ),
  Song(
    title: 'Blue in Green',
    artist: 'Miles Davis',
    youtubeUrl: 'https://www.youtube.com/watch?v=7D_ZkErg6tY',
    spotifyUrl: 'https://open.spotify.com/track/6FJ6vUq2c7UBo6Jf6aW5t6',
  ),
  Song(
    title: 'Island in the Sun',
    artist: 'Weezer',
    youtubeUrl: 'https://www.youtube.com/watch?v=HhWl0xs3JXs',
    spotifyUrl: 'https://open.spotify.com/track/4FL9tpjTGa19mYyI6t92bX',
  ),
  Song(
    title: 'The Less I Know the Better',
    artist: 'Tame Impala',
    youtubeUrl: 'https://www.youtube.com/watch?v=K2y2Ddi_T9k',
    spotifyUrl: 'https://open.spotify.com/track/3A2aFuUlgLOa5tOh9ldyzl',
  ),
  Song(
    title: 'Rising Sun',
    artist: 'The Doors',
    youtubeUrl: 'https://www.youtube.com/watch?v=e2hL85_g78E',
    spotifyUrl: 'https://open.spotify.com/track/4ikbh1H7rS60UjbWygby83',
  ),
  Song(
    title: 'Weight of Love',
    artist: 'The Black Keys',
    youtubeUrl: 'https://www.youtube.com/watch?v=6jtnk0i81uM',
    spotifyUrl: 'https://open.spotify.com/track/3hA3bSH5mU5nQrrECXN8jF',
  ),
  Song(
    title: 'La Femme d’Argent',
    artist: 'Air',
    youtubeUrl: 'https://www.youtube.com/watch?v=ZvU4n0ywXOU',
    spotifyUrl: 'https://open.spotify.com/track/4Tfl22hLFeKcfEmsSwnhbb',
  ),
  Song(
    title: 'Cold Little Heart',
    artist: 'Michael Kiwanuka',
    youtubeUrl: 'https://www.youtube.com/watch?v=wJzeU_U-kxw',
    spotifyUrl: 'https://open.spotify.com/track/0KM5w3Vje5jMGDgkPC98ZZ',
  ),
  Song(
    title: 'Killing Me Softly With His Song',
    artist: 'Fugees',
    youtubeUrl: 'https://www.youtube.com/watch?v=3UoWh6q7PbM',
    spotifyUrl: 'https://open.spotify.com/track/2d4j37fiwykCZsLfnnx77M',
  ),
  Song(
    title: 'Lush Life',
    artist: 'Zara Larsson',
    youtubeUrl: 'https://www.youtube.com/watch?v=tX_Ftz3kd7w',
    spotifyUrl: 'https://open.spotify.com/track/3S47Te58wCjmytmhQWEm17',
  ),
  Song(
    title: 'Numb',
    artist: 'Linkin Park',
    youtubeUrl: 'https://www.youtube.com/watch?v=kXYiU_JCYtU',
    spotifyUrl: 'https://open.spotify.com/track/0xy3Rpm7hXJlNw1Wz0U5YO',
  ),
  Song(
    title: 'All of Me',
    artist: 'John Legend',
    youtubeUrl: 'https://www.youtube.com/watch?v=450p7goxZqg',
    spotifyUrl: 'https://open.spotify.com/track/4cjlN1PcvqLgUAsISiv7k3',
  ),
  Song(
    title: 'Sunflower',
    artist: 'Post Malone ft. Swae Lee',
    youtubeUrl: 'https://www.youtube.com/watch?v=ApXoWvfEYVU',
    spotifyUrl: 'https://open.spotify.com/track/0R0u3n73c4uXbXndoeQJ3N',
  ),
  Song(
    title: 'Breezeblocks',
    artist: 'alt-J',
    youtubeUrl: 'https://www.youtube.com/watch?v=rVeMiVU77wo',
    spotifyUrl: 'https://open.spotify.com/track/6t9VdQLh03Z9d7q9Fec0kL',
  ),
  Song(
    title: 'Rocket Man',
    artist: 'Elton John',
    youtubeUrl: 'https://www.youtube.com/watch?v=dtVBCG6ThDk',
    spotifyUrl: 'https://open.spotify.com/track/0tFn33Aq1cbhsmZyZT4zGi',
  ),
];

