name: aupmoosic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  provider: ^6.0.5
  cupertino_icons: ^1.0.8

  table_calendar: ^3.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  # Remove the localizations block here, as it’s not needed directly under flutter
